#!/bin/sh

case $1 in
	"play")
		cmus-remote -u ;;
	"next")
		cmus-remote -n ;;
	"prev")
		cmus-remote -p ;;
esac

status() {
	if [ "$(cmus-remote -Q | grep status)" = "status playing" ]; then
		echo "Playing"
	else
		echo "Paused"		
	fi }

song=$(cmus-remote -Q | grep "tag title")
artist=$(cmus-remote -Q | grep "tag artist")
album=$(cmus-remote -Q | grep "tag album")
status="status" 

dunstify -h string:x-dunst-stack-tag:play -i "$HOME/.local/share/icons/Zafiro-icons/mimetypes/48/audio-mp3.svg" "$(eval ${status})" "<i>${song#*title }</i>\n${artist#*artist } - ${album#*album }"
